function com_opentext_cop_gwt_Cop(){var k=window,j=document,s=k.external,t,p,o='',w={},F=[],C=[],n=[],z,B;if(!k.__gwt_stylesLoaded){k.__gwt_stylesLoaded={};}if(!k.__gwt_scriptsLoaded){k.__gwt_scriptsLoaded={};}function u(){try{return s&&(s.gwtOnLoad&&k.location.search.indexOf('gwt.hybrid')== -1);}catch(a){return false;}}
function v(){if(t&&p){t(z,'com.opentext.cop.gwt.Cop',o);}}
function r(){var i,h;j.write('<script id="__gwt_marker_com.opentext.cop.gwt.Cop"><\/script>');h=j.getElementById('__gwt_marker_com.opentext.cop.gwt.Cop');if(h){i=h.previousSibling;}function d(b){var a=b.lastIndexOf('/');return a>=0?b.substring(0,a+1):'';}
;if(i&&i.src){o=d(i.src);}if(o==''){var c=j.getElementsByTagName('base');if(c.length>0){o=c[c.length-1].href;}else{var g=j.location;var e=g.href;o=d(e.substr(0,e.length-g.hash.length));}}else if(o.match(/^\w+:\/\//)){}else{var f=j.createElement('img');f.src=o+'clear.cache.gif';o=d(f.src);}if(h){h.parentNode.removeChild(h);}}
function A(){var f=document.getElementsByTagName('meta');for(var d=0,g=f.length;d<g;++d){var e=f[d],h=e.getAttribute('name'),b;if(h){if(h=='gwt:property'){b=e.getAttribute('content');if(b){var i,c=b.indexOf('=');if(c>=0){h=b.substring(0,c);i=b.substring(c+1);}else{h=b;i='';}w[h]=i;}}else if(h=='gwt:onPropertyErrorFn'){b=e.getAttribute('content');if(b){try{B=eval(b);}catch(a){alert('Bad handler "'+b+'" for "gwt:onPropertyErrorFn"');}}}else if(h=='gwt:onLoadErrorFn'){b=e.getAttribute('content');if(b){try{z=eval(b);}catch(a){alert('Bad handler "'+b+'" for "gwt:onLoadErrorFn"');}}}}}}
function m(a,b){return b in F[a];}
function l(a){var b=w[a];return b==null?null:b;}
function E(d,e){var a=n;for(var b=0,c=d.length-1;b<c;++b){a=a[d[b]]||(a[d[b]]=[]);}a[d[c]]=e;}
function q(d){var e=C[d](),b=F[d];if(e in b){return e;}var a=[];for(var c in b){a[b[c]]=c;}if(B){B(d,a,e);}throw null;}
C['locale']=function(){try{var g;if(g==null){var b=location.search;var h=b.indexOf('locale');if(h>=0){var e=b.substring(h);var c=e.indexOf('=')+1;var d=e.indexOf('&');if(d== -1){d=e.length;}g=e.substring(c,d);}}if(g==null){g=l('locale');}if(g==null){return 'default';}while(!m('locale',g)){var f=g.lastIndexOf('_');if(f== -1){g='default';break;}else{g=g.substring(0,f);}}return g;}catch(a){alert('Unexpected exception in locale detection, using default: '+a);return 'default';}};F['locale']={'default':0,'fr':1};C['user.agent']=function(){var d=navigator.userAgent.toLowerCase();var b=function(a){return parseInt(a[1])*1000+parseInt(a[2]);};if(d.indexOf('opera')!= -1){return 'opera';}else if(d.indexOf('webkit')!= -1){return 'safari';}else if(d.indexOf('msie')!= -1){var c=/msie ([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=6000){return 'ie6';}}}else if(d.indexOf('gecko')!= -1){var c=/rv:([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=1008)return 'gecko1_8';}return 'gecko';}return 'unknown';};F['user.agent']={'gecko':0,'gecko1_8':1,'ie6':2,'opera':3,'safari':4};com_opentext_cop_gwt_Cop.onScriptLoad=function(a){com_opentext_cop_gwt_Cop=null;t=a;v();};r();A();var y;function x(){if(!p){p=true;v();if(j.removeEventListener){j.removeEventListener('DOMContentLoaded',x,false);}if(y){clearInterval(y);}}}
if(j.addEventListener){j.addEventListener('DOMContentLoaded',x,false);}var y=setInterval(function(){if(/loaded|complete/.test(j.readyState)){x();}},50);var D;try{E(['fr','opera'],'23C946DAFCAC0FEA1A41677585567F11');E(['default','ie6'],'26573E8FE75B229B24D8A81169E5B513');E(['fr','ie6'],'280490E57CCD6685C3167F75CF43D083');E(['fr','safari'],'63A3D0A3F0854400D9E1D18A41955FC2');E(['default','opera'],'74259F94CFC90534AEFEE30756BF2A2A');E(['fr','gecko'],'87AA86795CEC607538990C0A8A7DF397');E(['fr','gecko1_8'],'8B8BB385A1B1EC90C51A145BB30E71CE');E(['default','gecko'],'A2C34239B51391DB30976CDB702A12EB');E(['default','safari'],'E11AD39DF82CE22C9BE36B70A0A418BE');E(['default','gecko1_8'],'E4CC19F7EEA72818727A3A1045E5EE4D');D=n[q('locale')][q('user.agent')];}catch(a){return;}D+='.cache.js';if(!__gwt_stylesLoaded['skye.css']){__gwt_stylesLoaded['skye.css']=true;document.write('<link rel="stylesheet" href="'+o+'skye.css">');}if(!__gwt_stylesLoaded['copgwt.css']){__gwt_stylesLoaded['copgwt.css']=true;document.write('<link rel="stylesheet" href="'+o+'copgwt.css">');}j.write('<script src="'+o+D+'"><\/script>');}
com_opentext_cop_gwt_Cop.__gwt_initHandlers=function(i,e,j){var d=window,g=d.onresize,f=d.onbeforeunload,h=d.onunload;d.onresize=function(a){try{i();}finally{g&&g(a);}};d.onbeforeunload=function(a){var c,b;try{c=e();}finally{b=f&&f(a);}if(c!=null){return c;}if(b!=null){return b;}};d.onunload=function(a){try{j();}finally{h&&h(a);}};};com_opentext_cop_gwt_Cop();