var XMLExport = new function() 
{	
	return {
		doSubmit: function() 
		{
			var theForm = document.xmlExportForm;
			var exportVersions = $( 'input:radio[name=exportVersions]:checked' ).val();
			var scopeSelect = $( 'input:radio[name=scopeSelect]:checked' ).val();
			var versionNumber = parseInt( theForm.versionNumber.value );
			var scopeNumber = parseInt( theForm.scopeNumber.value );
			var ok = true;
		
			// Check that an object has been selected
			
			if ( document.xmlExportForm.objID.value == '' )
			{
				ok = false;
				alert( LocString( 'No object has been selected to export.', xmlExportStr ) );
			}
			
			// Check the export versions radio buttons.  If "all" or "current", then
			// pass those values to the export action.  If it's a specific version, then
			// get the version number as input.  Otherwise, don't pass the versionInfo
			// parameter
			
			if ( ok )
			{
				if ( exportVersions == 'all' || exportVersions == 'current' )
				{
					theForm.versionInfo.value = exportVersions;
					theForm.versionInfo.disabled = false;
				}
				else if ( exportVersions == 'specific' )
				{
					// Make sure that a number was entered for the version if "specific" is selected
					
					if ( isNaN( versionNumber ) ) 
					{
						alert( LocString( 'Version number must be specified.', xmlExportStr ) );
						ok = false;
					}
					else if ( versionNumber <= 0 )
					{
						alert( LocString( 'Version number must be greater than zero.', xmlExportStr ) );
						ok = false;
					}
					else
					{
						theForm.versionInfo.value = versionNumber;
						theForm.versionInfo.disabled = false;
					}
				}
				else
				{
					theForm.versionInfo.disabled = true;
				}
			}

			// Check the scope radio buttons.  If "base", "sub", or "one", then
			// pass those values to the export action.  If it's a specific scope, then
			// get the number as input.  
			
			if ( ok )
			{ 
				if ( scopeSelect == 'specific' )
				{
					if ( isNaN( scopeNumber ) )
					{
						alert( LocString( 'Scope must be specified.', xmlExportStr ) );
						ok = false;
					}
					else if ( scopeNumber <= 0 )
					{
						alert( LocString( 'Scope must be greater than zero.', xmlExportStr ) );
						ok = false;
					}
					else
					{
						theForm.scope.value = scopeNumber;
					}
				}
				else
				{
					theForm.scope.value = scopeSelect;
				}
			}
			
			if ( ok )
			{
				theForm.submit();
			}
		}
	}
};

$( function() {

	// When the "Generate content" checkbox is checked, version info must be exported
	// (i.e. the "None" radio button will be disabled).  When "Generate content" is
	// unchecked, none of the content export options will be enabled.
	
	$( '#generateContent' ).change( function() {
		if ( $( '#generateContent' ).is( ':checked' ) )
		{
			if ( $( '#exportVersionsNone' ).is( ':checked' ) )
			{
				$( '#exportVersionsNone' ).attr( 'checked', false );
				$( '#exportVersionsAll' ).attr( 'checked', true );
			}
			$( '#exportVersionsNone' ).attr( 'disabled', true );
			$( 'input[name=content]' ).removeAttr( 'disabled' );
		}
		else
		{
			$( '#exportVersionsNone' ).removeAttr( 'disabled' );
			$( 'input[name=content]' ).attr( 'disabled', true );
		}
		
	} );
	
	// When the Generate permissions checkbox is checked, automatically check the
	// acls box, because ACLs do get automatically generated by the export action if
	// you ask for permissions

	$( '#generatePermissions' ).change( function() {
		if ( $( '#generatePermissions' ).is( ':checked' ) )
		{
			$( '#generateACLs' ).attr( 'checked', true );
			$( '#generateACLs' ).attr( 'disabled', true );
		}
		else
		{
			$( '#generateACLs' ).removeAttr( 'disabled' );
			$( '#generateACLs' ).attr( 'checked', false );
		}
	} );

	$( '#exportVersionsSpecific' ).click( function() { $( '#versionNumber' ).focus(); } );	
	$( '#versionNumber' ).bind( 'keyup', function() { $( '#exportVersionsSpecific' ).attr( 'checked', true ); } );
	$( '#scopeSelectSpecific' ).click( function() { $( '#scopeNumber' ).focus(); } );
	$( '#scopeNumber' ).bind( 'keyup', function() { $( '#scopeSelectSpecific' ).attr( 'checked', true ); } );
} );